-- Every entity a report can be about, from two populations:
--
--   * registered CTI entities, which carry a cti_id and the full attribute set
--   * label-only entities, named on a report but never registered
--
-- Unlike the other dimensions this one MERGEs rather than only inserting,
-- because an entity's attributes genuinely change -- a client changes sector,
-- gains a prm_id, corrects its name. The MERGE updates those in place and never
-- touches id, so the key survives every attribute change.
--
-- The id is a Delta identity column and the table is never replaced, so an
-- entity keeps the id it was first given. Back this table up: it cannot be
-- rebuilt from the source alone. Identity values have gaps -- that is normal.
--
-- BY DEFAULT rather than ALWAYS so the id = -1 'Unknown' row can be written
-- explicitly. -1 is the only id ever inserted by hand.

CREATE TABLE IF NOT EXISTS {{ target_schema }}.dim_entity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  entity_natural_key STRING,
  cti_id STRING,
  prm_id STRING,
  entity_name_en STRING,
  entity_name_ar STRING,
  country STRING,
  category STRING,
  sector STRING,
  entity_type STRING,
  domain STRING,
  is_cti_entity BOOLEAN,
  first_seen_at TIMESTAMP
) USING DELTA;

-- The Unknown member, so fact_report never carries a NULL foreign key.
-- Its natural key is NULL, which never matches in the MERGE below, so the row
-- cannot be overwritten by a real entity.
INSERT INTO {{ target_schema }}.dim_entity
  (id, entity_natural_key, entity_name_en, entity_name_ar, is_cti_entity, first_seen_at)
SELECT -1, NULL, 'Unknown', 'غير معروف', false, current_timestamp()
FROM (SELECT 1) seed
WHERE NOT EXISTS (
  SELECT 1
  FROM {{ target_schema }}.dim_entity existing
  WHERE existing.id = -1
);

-- The entity list as the source currently describes it.
CREATE OR REPLACE TEMP VIEW entity_source AS
WITH cti_entities AS (
  SELECT
    trim(cti_id) AS cti_id,
    CASE WHEN upper(trim(prm_id))         IN ('NULL', 'NUL', '') THEN NULL ELSE trim(prm_id)         END AS prm_id,
    CASE WHEN upper(trim(client_name_en)) IN ('NULL', 'NUL', '') THEN NULL ELSE trim(client_name_en) END AS entity_name_en,
    CASE WHEN upper(trim(client_name_ar)) IN ('NULL', 'NUL', '') THEN NULL ELSE trim(client_name_ar) END AS entity_name_ar,
    CASE WHEN upper(trim(country))        IN ('NULL', 'NUL', '') THEN NULL ELSE trim(country)        END AS country,
    CASE WHEN upper(trim(category))       IN ('NULL', 'NUL', '') THEN NULL ELSE trim(category)       END AS category,
    CASE WHEN upper(trim(sector))         IN ('NULL', 'NUL', '') THEN NULL ELSE trim(sector)         END AS sector,
    CASE WHEN upper(trim(type_of_entity)) IN ('NULL', 'NUL', '') THEN NULL ELSE trim(type_of_entity) END AS entity_type,
    CASE WHEN upper(trim(domain))         IN ('NULL', 'NUL', '') THEN NULL ELSE trim(domain)         END AS domain,
    true AS is_cti_entity
  FROM {{ source_schema }}.entities
  WHERE cti_id IS NOT NULL
),

-- One row per cti_id.
registered AS (
  SELECT
    cti_id, prm_id, entity_name_en, entity_name_ar,
    country, category, sector, entity_type, domain, is_cti_entity
  FROM (
    SELECT
      *,
      row_number() OVER (PARTITION BY cti_id ORDER BY entity_name_en) AS row_num
    FROM cti_entities
  ) ranked
  WHERE row_num = 1
),

-- entities_names_ar is pipe separated. '\\|' because split() takes a regex.
report_labels AS (
  SELECT DISTINCT
    trim(value) AS entity_name_ar
  FROM {{ source_schema }}.rasd
  LATERAL VIEW explode(split(coalesce(entities_names_ar, ''), '\\|')) exploded AS value
  WHERE report_type = 'rasd'
    AND entities_cti_id IS NULL
    AND trim(value) <> ''
),

label_only AS (
  SELECT
    CAST(NULL AS STRING) AS cti_id,
    CAST(NULL AS STRING) AS prm_id,
    l.entity_name_ar AS entity_name_en,  -- the source carries no English label here
    l.entity_name_ar,
    CAST(NULL AS STRING) AS country,
    CAST(NULL AS STRING) AS category,
    CAST(NULL AS STRING) AS sector,
    CAST(NULL AS STRING) AS entity_type,
    CAST(NULL AS STRING) AS domain,
    false AS is_cti_entity
  FROM report_labels l
  WHERE NOT EXISTS (
    SELECT 1
    FROM registered r
    WHERE upper(r.entity_name_ar) = upper(l.entity_name_ar)
  )
),

all_entities AS (
  SELECT * FROM registered
  UNION ALL
  SELECT * FROM label_only
)

SELECT
  -- What the id is minted from. cti_id for a registered entity, so a client
  -- renaming itself keeps its key. A label-only entity has nothing but its
  -- name, so renaming one does mint a new key -- the source carries no
  -- identifier that would tie the old name to the new one.
  upper(coalesce(cti_id, entity_name_ar)) AS entity_natural_key,
  cti_id,
  prm_id,
  entity_name_en,
  entity_name_ar,
  country,
  category,
  sector,
  entity_type,
  domain,
  is_cti_entity
FROM all_entities;

-- Refresh attributes in place, add entities we have not seen before, and leave
-- the id of everything that already exists exactly as it is. Entities that have
-- left the source keep their row so old reports still resolve their id.
MERGE INTO {{ target_schema }}.dim_entity AS target
USING entity_source AS source
ON target.entity_natural_key = source.entity_natural_key

WHEN MATCHED THEN UPDATE SET
  target.cti_id = source.cti_id,
  target.prm_id = source.prm_id,
  target.entity_name_en = source.entity_name_en,
  target.entity_name_ar = source.entity_name_ar,
  target.country = source.country,
  target.category = source.category,
  target.sector = source.sector,
  target.entity_type = source.entity_type,
  target.domain = source.domain,
  target.is_cti_entity = source.is_cti_entity

WHEN NOT MATCHED THEN INSERT (
  entity_natural_key, cti_id, prm_id, entity_name_en, entity_name_ar,
  country, category, sector, entity_type, domain, is_cti_entity, first_seen_at
) VALUES (
  source.entity_natural_key, source.cti_id, source.prm_id,
  source.entity_name_en, source.entity_name_ar, source.country, source.category,
  source.sector, source.entity_type, source.domain, source.is_cti_entity,
  current_timestamp()
)
