-- One row per evidence type ever seen on a RASD report.
--
-- Append-only, with the id minted by a Delta identity column, so a evidence type keeps
-- the id it was first given no matter what arrives later. Before this the id was
-- row_number() over an alphabetical sort, so a new evidence type shifted every id after
-- it. The business reports against these ids, which means:
--
--   * never CREATE OR REPLACE this table -- that re-mints every id
--   * back it up. It cannot be rebuilt from the source alone any more
--
-- Identity values are unique and increasing but NOT contiguous. Gaps are normal.
--
-- BY DEFAULT rather than ALWAYS so the id = -1 'Unknown' row can be written
-- explicitly. -1 is the only id ever inserted by hand -- everything else must let
-- Delta assign it.
--
-- A evidence type that disappears from the source keeps its row, so a report built
-- before it vanished still resolves its id to a name.

CREATE TABLE IF NOT EXISTS {{ target_schema }}.dim_evidence_type (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  evidence_type_name STRING,
  first_seen_at TIMESTAMP
) USING DELTA;

-- The Unknown member, so fact_report never carries a NULL foreign key.
INSERT INTO {{ target_schema }}.dim_evidence_type (id, evidence_type_name, first_seen_at)
SELECT -1, 'Unknown', current_timestamp()
FROM (SELECT 1) seed
WHERE NOT EXISTS (
  SELECT 1
  FROM {{ target_schema }}.dim_evidence_type existing
  WHERE existing.id = -1
);

-- New values only. Existing rows are never updated or deleted.
INSERT INTO {{ target_schema }}.dim_evidence_type (evidence_type_name, first_seen_at)
SELECT
  candidates.evidence_type_name,
  current_timestamp()
FROM (
  SELECT DISTINCT evidence_type_name
  FROM {{ target_schema }}.stg_report
  WHERE evidence_type_name IS NOT NULL
) candidates
WHERE NOT EXISTS (
  SELECT 1
  FROM {{ target_schema }}.dim_evidence_type existing
  WHERE upper(existing.evidence_type_name) = upper(candidates.evidence_type_name)
)
