-- One row per importance level ever seen on a RASD report.
--
-- Append-only, with the id minted by a Delta identity column, so a importance level keeps
-- the id it was first given no matter what arrives later. Before this the id was
-- row_number() over an alphabetical sort, so a new importance level shifted every id after
-- it. The business reports against these ids, which means:
--
--   * never CREATE OR REPLACE this table -- that re-mints every id
--   * back it up. It cannot be rebuilt from the source alone any more
--
-- Identity values are unique and increasing but NOT contiguous. Gaps are normal.
--
-- BY DEFAULT rather than ALWAYS so the id = -1 'Unknown' row can be written
-- explicitly. -1 is the only id ever inserted by hand -- everything else must let
-- Delta assign it.
--
-- A importance level that disappears from the source keeps its row, so a report built
-- before it vanished still resolves its id to a name.

CREATE TABLE IF NOT EXISTS {{ target_schema }}.dim_importance_level (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  importance_level STRING,
  first_seen_at TIMESTAMP
) USING DELTA;

-- The Unknown member, so fact_report never carries a NULL foreign key.
INSERT INTO {{ target_schema }}.dim_importance_level (id, importance_level, first_seen_at)
SELECT -1, 'Unknown', current_timestamp()
FROM (SELECT 1) seed
WHERE NOT EXISTS (
  SELECT 1
  FROM {{ target_schema }}.dim_importance_level existing
  WHERE existing.id = -1
);

-- New values only. Existing rows are never updated or deleted.
INSERT INTO {{ target_schema }}.dim_importance_level (importance_level, first_seen_at)
SELECT
  candidates.importance_level,
  current_timestamp()
FROM (
  SELECT DISTINCT importance_level
  FROM {{ target_schema }}.stg_report
  WHERE importance_level IS NOT NULL
) candidates
WHERE NOT EXISTS (
  SELECT 1
  FROM {{ target_schema }}.dim_importance_level existing
  WHERE upper(existing.importance_level) = upper(candidates.importance_level)
)
