-- One row per threat group ever seen on a RASD report.
--
-- Append-only, with the id minted by a Delta identity column, so a threat group keeps
-- the id it was first given no matter what arrives later. Before this the id was
-- row_number() over an alphabetical sort, so a new threat group shifted every id after
-- it. The business reports against these ids, which means:
--
--   * never CREATE OR REPLACE this table -- that re-mints every id
--   * back it up. It cannot be rebuilt from the source alone any more
--
-- Identity values are unique and increasing but NOT contiguous. Gaps are normal.
--
-- BY DEFAULT rather than ALWAYS so the id = -1 'Unknown' row can be written
-- explicitly. -1 is the only id ever inserted by hand -- everything else must let
-- Delta assign it.
--
-- A threat group that disappears from the source keeps its row, so a report built
-- before it vanished still resolves its id to a name.

CREATE TABLE IF NOT EXISTS {{ target_schema }}.dim_group (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  group_name STRING,
  first_seen_at TIMESTAMP
) USING DELTA;

-- The Unknown member, so fact_report never carries a NULL foreign key.
INSERT INTO {{ target_schema }}.dim_group (id, group_name, first_seen_at)
SELECT -1, 'Unknown', current_timestamp()
FROM (SELECT 1) seed
WHERE NOT EXISTS (
  SELECT 1
  FROM {{ target_schema }}.dim_group existing
  WHERE existing.id = -1
);

-- New values only. Existing rows are never updated or deleted.
INSERT INTO {{ target_schema }}.dim_group (group_name, first_seen_at)
SELECT
  candidates.group_name,
  current_timestamp()
FROM (
  SELECT DISTINCT trim(label) AS group_name
  FROM {{ target_schema }}.stg_report
  LATERAL VIEW explode(group_labels) exploded AS label
  WHERE trim(label) <> ''
) candidates
WHERE NOT EXISTS (
  SELECT 1
  FROM {{ target_schema }}.dim_group existing
  WHERE upper(existing.group_name) = upper(candidates.group_name)
)
