{#
  Macro to generate surrogate keys that work across multiple engines
  For PostgreSQL: Uses IDENTITY or SERIAL
  For Spark: Uses monotonically_increasing_id() or row_number()
  For Trino: Uses row_number() over()
#}

{% macro generate_surrogate_key(column_list) %}
  {%- set engine = target.type | lower -%}
  
  {%- if engine == 'postgres' -%}
    -- PostgreSQL: Use IDENTITY or SERIAL
    {{ column_list }} INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    
  {%- elif engine == 'spark' -%}
    -- Spark: Use row_number() over() since monotonically_increasing_id() isn't deterministic
    CAST(ROW_NUMBER() OVER (ORDER BY {{ column_list }}) AS INTEGER) AS {{ column_list }}
    
  {%- elif engine == 'trino' -%}
    -- Trino: Use row_number() over()
    CAST(ROW_NUMBER() OVER (ORDER BY {{ column_list }}) AS INTEGER) AS {{ column_list }}
    
  {%- else -%}
    -- Default: Use row_number() for other engines
    CAST(ROW_NUMBER() OVER (ORDER BY {{ column_list }}) AS INTEGER) AS {{ column_list }}
    
  {%- endif -%}
{% endmacro %}